### ISSUE TITLE
Background layer seems to be offset

### ISSUE THREAD

**Issue by liamkennedy** [chinasaur/poptart#2]
Great piece of code.   I've been making a few additions for my own use.   

When I tried to implement a non-transparent background I found what appears to be a bug (not sure if it is with your code - or the underlying code).  

If you make the text background anything other than fully transparent you'll notice the background either does not appear (for small pieces of text) - or - if you provide a long enough piece of text you eventually see part of the background on the left side of your text only.  

What appears to be happening is the background portion always starts with x_offset of '0'.   

As a test make the following change to the render_toast function.  (change on line 177 only)
   s = graphics_resource_render_text_ext(img, x_offset, y_offset,
                                     GRAPHICS_RESOURCE_WIDTH,
                                     GRAPHICS_RESOURCE_HEIGHT,
                                     GRAPHICS_RGBA32(0xff,0xff,0xff,0xff), /\* fg _/
                                     GRAPHICS_RGBA32(255,255,255,0xff), /_ bg */
                                     text, 0, text_size);

Make the file then test it 
poptart 'This is a really long piece of text blah blah' -s 70

You should see the white background does not extend to the full width of the text.

If you modify the code to re-set the x-offset to zero - you'll see the whole text has the background visible.  

   s = graphics_resource_render_text_ext(img, 0, y_offset,
                                     GRAPHICS_RESOURCE_WIDTH,
                                     GRAPHICS_RESOURCE_HEIGHT,
                                     GRAPHICS_RGBA32(0xff,0xff,0xff,0xff), /\* fg _/
                                     GRAPHICS_RGBA32(255,255,255,0xff), /_ bg */
                                     text, 0, text_size);

First... can you reproduce this?

And... any ideas on a work-around?

THANKS!

**Comment by chinasaur** [comment]
I have a fix, but it's in upstream vgfont lib.  Will send to raspi/firmware and try to put in workaround for poptart for now.

**Comment by chinasaur** [comment]
Here's the pull request upstream: https://github.com/raspberrypi/firmware/pull/308
I can probably just add some pieces of vgfont to this repo and have it link in that in the interim until that pull is accepted.

**Comment by liamkennedy** [comment]
Thanks so much for the update and taking a look at the issue.

**Comment by chinasaur** [comment]
So, the patch above fixes the x-offset issue (and that has been pulled into raspberrypi/userland so should be in a future release; for now I'm including a patched vgfont in poptart).

Unfortunately there's still an issue with background color for text with newlines.  I have a pretty good handle on what the issue is, and can patch it when I find some time.  I think we'd probably like to be able to control how much padding to add to the background colored area around the edges of the text too, so that would be an added feature.

**Comment by liamkennedy** [comment]
That's spectacular news!   Thank you for doing this - it is much appreciated.

**Comment by chinasaur** [comment]
Okay, I corrected the y-offset issue with background rendering for multiline text.  Sent it upstream here: https://github.com/raspberrypi/userland/pull/195

It's a little bit bigger patch than the previous one, so may take longer to be pulled in.  But it's fixed in the local copy of vgfont that currently ships with poptart.

I'd still like to add background rendering with padding, or in the case of scrolling text it should probably be background covering the whole x extent of the screen?

**Comment by nagualcode** [comment]
Hello, 
please add colors instructions at poptart -help 
Thank you.
